--------------------------------------------------------
--  Fichier créé - dimanche-janvier-03-2021   
--------------------------------------------------------
DROP SEQUENCE "ID";
DROP SEQUENCE "ID_COMP";
DROP SEQUENCE "ID_MARCHAND";
DROP SEQUENCE "ID_RAMASSAGE";
DROP SEQUENCE "ID_RECLAMATION";
DROP SEQUENCE "ID_RESSOURCES";
DROP SEQUENCE "ID_ZONEVERTE";
DROP TABLE "CITOYENS" cascade constraints;
DROP TABLE "COMPTE" cascade constraints;
DROP TABLE "EMPLOYE" cascade constraints;
DROP TABLE "EMPLOYE_RAMASSAGE" cascade constraints;
DROP TABLE "EVENEMENT" cascade constraints;
DROP TABLE "MARCHAND" cascade constraints;
DROP TABLE "MISSION" cascade constraints;
DROP TABLE "RAMASSAGE" cascade constraints;
DROP TABLE "RECLAMATION" cascade constraints;
DROP TABLE "RESSOURCE" cascade constraints;
DROP TABLE "ZONE_VERTE" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence ID
--------------------------------------------------------

   CREATE SEQUENCE  "ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_COMP
--------------------------------------------------------

   CREATE SEQUENCE  "ID_COMP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_MARCHAND
--------------------------------------------------------

   CREATE SEQUENCE  "ID_MARCHAND"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_RAMASSAGE
--------------------------------------------------------

   CREATE SEQUENCE  "ID_RAMASSAGE"  MINVALUE 100 MAXVALUE 9999999999999999999999999999 INCREMENT BY 11 START WITH 8965 CACHE 200 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_RECLAMATION
--------------------------------------------------------

   CREATE SEQUENCE  "ID_RECLAMATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_RESSOURCES
--------------------------------------------------------

   CREATE SEQUENCE  "ID_RESSOURCES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_ZONEVERTE
--------------------------------------------------------

   CREATE SEQUENCE  "ID_ZONEVERTE"  MINVALUE 100 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 520686 CACHE 20000 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CITOYENS
--------------------------------------------------------

  CREATE TABLE "CITOYENS" 
   (	"ID_CIT" VARCHAR2(20 BYTE), 
	"NOM_CIT" VARCHAR2(20 BYTE), 
	"PRENOM_CIT" VARCHAR2(20 BYTE), 
	"SEXE_CIT" VARCHAR2(20 BYTE), 
	"DATE_CIT" VARCHAR2(20 BYTE), 
	"LIEU_CIT" VARCHAR2(20 BYTE), 
	"MAIL_CIT" VARCHAR2(20 BYTE), 
	"TEL_CIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPTE
--------------------------------------------------------

  CREATE TABLE "COMPTE" 
   (	"IDENTIFIANT" VARCHAR2(20 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(20 BYTE), 
	"TYPE_AUTHEN" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "EMPLOYE" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(40 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE_RAMASSAGE
--------------------------------------------------------

  CREATE TABLE "EMPLOYE_RAMASSAGE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"ID_RAMASSAGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "EVENEMENT" 
   (	"ID_EVENT" VARCHAR2(20 BYTE), 
	"NOM_EVENT" VARCHAR2(20 BYTE), 
	"TYPE_EVENT" VARCHAR2(20 BYTE), 
	"DATE_EVENT" VARCHAR2(20 BYTE), 
	"HOR_EVENT" VARCHAR2(20 BYTE), 
	"EMPL_EVENT" VARCHAR2(20 BYTE), 
	"ETAT_EVENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARCHAND
--------------------------------------------------------

  CREATE TABLE "MARCHAND" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "MISSION" 
   (	"CIN" NUMBER, 
	"HORAIRE" VARCHAR2(20 BYTE), 
	"DATE_MISSION" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RAMASSAGE
--------------------------------------------------------

  CREATE TABLE "RAMASSAGE" 
   (	"ID_RAMASSAGE" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"DATE_RAMASSAGE" VARCHAR2(40 BYTE), 
	"NOMBRE_POUBELLE" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"NOM_CARTIER" VARCHAR2(20 BYTE), 
	"HEURE_DEBUT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "RECLAMATION" 
   (	"NOM_ROUTE" VARCHAR2(20 BYTE), 
	"TYPE_PANNE" VARCHAR2(20 BYTE), 
	"DATE_RECLAMAT" VARCHAR2(40 BYTE), 
	"NATURE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"ID_COMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESSOURCE
--------------------------------------------------------

  CREATE TABLE "RESSOURCE" 
   (	"TYPE_COMPOSANT" VARCHAR2(20 BYTE), 
	"ETAT_COMPOSANT" VARCHAR2(20 BYTE), 
	"NOM_ROUTE" VARCHAR2(20 BYTE), 
	"POSX" FLOAT(126), 
	"POSY" FLOAT(126), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ZONE_VERTE
--------------------------------------------------------

  CREATE TABLE "ZONE_VERTE" 
   (	"ID_ZONEVERTE" NUMBER, 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"AIRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CITOYENS
SET DEFINE OFF;
Insert into CITOYENS (ID_CIT,NOM_CIT,PRENOM_CIT,SEXE_CIT,DATE_CIT,LIEU_CIT,MAIL_CIT,TEL_CIT) values ('1000','cccccc','dddd','Femme','01/02/1996','fggg','aa@hhh.com','22335566');
REM INSERTING into COMPTE
SET DEFINE OFF;
Insert into COMPTE (IDENTIFIANT,MOT_DE_PASSE,TYPE_AUTHEN,CIN) values ('1000','120','Administrateur','07245656');
Insert into COMPTE (IDENTIFIANT,MOT_DE_PASSE,TYPE_AUTHEN,CIN) values ('9999','1234','Agent','07888888');
REM INSERTING into EMPLOYE
SET DEFINE OFF;
Insert into EMPLOYE (NOM,PRENOM,MAIL,TYPE,CIN,ETAT) values (null,null,null,null,'01010101',null);
Insert into EMPLOYE (NOM,PRENOM,MAIL,TYPE,CIN,ETAT) values ('azer','zaza','wassim.khemiri@esprit.tn','Agent','02020202','Present');
Insert into EMPLOYE (NOM,PRENOM,MAIL,TYPE,CIN,ETAT) values ('qqq','ddd','rima.ibri@esprit.tn','Secretaire','03030303','Present');
Insert into EMPLOYE (NOM,PRENOM,MAIL,TYPE,CIN,ETAT) values (null,null,null,null,'07245656',null);
Insert into EMPLOYE (NOM,PRENOM,MAIL,TYPE,CIN,ETAT) values (null,null,null,null,'07333333',null);
REM INSERTING into EMPLOYE_RAMASSAGE
SET DEFINE OFF;
Insert into EMPLOYE_RAMASSAGE (CIN,ID_RAMASSAGE) values ('01010101','6765');
Insert into EMPLOYE_RAMASSAGE (CIN,ID_RAMASSAGE) values ('07245656','6765');
Insert into EMPLOYE_RAMASSAGE (CIN,ID_RAMASSAGE) values ('07333333','6765');
REM INSERTING into EVENEMENT
SET DEFINE OFF;
Insert into EVENEMENT (ID_EVENT,NOM_EVENT,TYPE_EVENT,DATE_EVENT,HOR_EVENT,EMPL_EVENT,ETAT_EVENT) values ('1000','aaa','rrr','01/02/2020','11H22','hjjh','passe');
Insert into EVENEMENT (ID_EVENT,NOM_EVENT,TYPE_EVENT,DATE_EVENT,HOR_EVENT,EMPL_EVENT,ETAT_EVENT) values ('8000','aaa','rrr','01/02/2020','11H22','hjjh','passe');
Insert into EVENEMENT (ID_EVENT,NOM_EVENT,TYPE_EVENT,DATE_EVENT,HOR_EVENT,EMPL_EVENT,ETAT_EVENT) values ('7000','aaa','rrr','01/02/2020','11H22','hjjh','en cours');
REM INSERTING into MARCHAND
SET DEFINE OFF;
Insert into MARCHAND (ID,NOM,PRENOM,EMPLACEMENT,NUMERO) values ('2','a','deed','dsqsdq','1000');
Insert into MARCHAND (ID,NOM,PRENOM,EMPLACEMENT,NUMERO) values ('3','b','deed','dsqsdq','1000');
REM INSERTING into MISSION
SET DEFINE OFF;
Insert into MISSION (CIN,HORAIRE,DATE_MISSION,TYPE,EMPLACEMENT) values ('7245656','01:20','02/02/20','uh','drety');
REM INSERTING into RAMASSAGE
SET DEFINE OFF;
Insert into RAMASSAGE (ID_RAMASSAGE,MATRICULE,DATE_RAMASSAGE,NOMBRE_POUBELLE,DUREE,NOM_CARTIER,HEURE_DEBUT) values ('6765','120TN1111','01/01/2020','10','00:10','EL Menzah 5 ','08:00:00');
REM INSERTING into RECLAMATION
SET DEFINE OFF;
Insert into RECLAMATION (NOM_ROUTE,TYPE_PANNE,DATE_RECLAMAT,NATURE,ID,ID_COMP) values ('Nkhilette','potraux electrique','dim. janv. 3 2021','Urgente','83','3');
Insert into RECLAMATION (NOM_ROUTE,TYPE_PANNE,DATE_RECLAMAT,NATURE,ID,ID_COMP) values ('Ghazela','potraux electrique','dim. janv. 3 2021','Urgente','82','3');
REM INSERTING into RESSOURCE
SET DEFINE OFF;
Insert into RESSOURCE (TYPE_COMPOSANT,ETAT_COMPOSANT,NOM_ROUTE,POSX,POSY,ID) values ('Canal d''Eau','En Panne','Nkhilette','0','0','4');
Insert into RESSOURCE (TYPE_COMPOSANT,ETAT_COMPOSANT,NOM_ROUTE,POSX,POSY,ID) values ('Poteau Electrique','Fonctionne',null,'0','0','5');
Insert into RESSOURCE (TYPE_COMPOSANT,ETAT_COMPOSANT,NOM_ROUTE,POSX,POSY,ID) values ('Canal d''Eau','En Panne','Ghazela','0','0','3');
REM INSERTING into ZONE_VERTE
SET DEFINE OFF;
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('616','uuu','Rue Kaboul','500');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('560','juju','Amilcar','156');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('570','lkhjk','Rue Kaboul','123');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('593','kok','Amilcar','255');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('460639','oo','Amilcar','100');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('460686','pyy','Amilcar','1450');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('460685','ppp','Amilcar','900');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('460687','uuuuu','Rue Kaboul','1500');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('460688','aze','Amilcar','1200');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('480686','momomo','Amilcar','1300');
Insert into ZONE_VERTE (ID_ZONEVERTE,LIBELLE,ADRESSE,AIRE) values ('500686','aze','Amilcar','1200');
--------------------------------------------------------
--  DDL for Index PK24
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK24" ON "MARCHAND" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RAMASSAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAMASSAGE_PK" ON "RAMASSAGE" ("ID_RAMASSAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYE_PK" ON "EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK66
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK66" ON "COMPTE" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK23
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK23" ON "EVENEMENT" ("ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK102
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK102" ON "EMPLOYE_RAMASSAGE" ("CIN", "ID_RAMASSAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECLAMATION_PK" ON "RECLAMATION" ("ID", "ID_COMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ZONE_VERTE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZONE_VERTE_PK1" ON "ZONE_VERTE" ("ID_ZONEVERTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RAMASSAGE_INDEX1
--------------------------------------------------------

  CREATE INDEX "RAMASSAGE_INDEX1" ON "RAMASSAGE" ("DATE_RAMASSAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK22
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK22" ON "CITOYENS" ("ID_CIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK25
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK25" ON "MISSION" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESSOURCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESSOURCE_PK" ON "RESSOURCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MARCHANT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MARCHANT_TRIGGER" before insert on marchand for each row begin:new.ID:=ID_marchand.nextval;End;
/
ALTER TRIGGER "MARCHANT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECLAMATION_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RECLAMATION_TRIGGER" 
BEFORE INSERT ON RECLAMATION 
FOR EACH ROW
BEGIN 
:new.ID:= ID_Reclamation.nextval; 
END; 


/
ALTER TRIGGER "RECLAMATION_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESSOURCES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RESSOURCES_TRIGGER" before insert on ressource for each row begin:new.ID:=ID_ressources.nextval;End;
/
ALTER TRIGGER "RESSOURCES_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ZONE_VERTE
--------------------------------------------------------

  ALTER TABLE "ZONE_VERTE" MODIFY ("ID_ZONEVERTE" NOT NULL ENABLE);
  ALTER TABLE "ZONE_VERTE" ADD CONSTRAINT "ZONE_VERTE_PK" PRIMARY KEY ("ID_ZONEVERTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE_RAMASSAGE
--------------------------------------------------------

  ALTER TABLE "EMPLOYE_RAMASSAGE" ADD CONSTRAINT "PK102" PRIMARY KEY ("CIN", "ID_RAMASSAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESSOURCE
--------------------------------------------------------

  ALTER TABLE "RESSOURCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RESSOURCE" ADD CONSTRAINT "RESSOURCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPTE
--------------------------------------------------------

  ALTER TABLE "COMPTE" ADD CONSTRAINT "PK66" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "EVENEMENT" ADD CONSTRAINT "PK23" PRIMARY KEY ("ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RAMASSAGE
--------------------------------------------------------

  ALTER TABLE "RAMASSAGE" MODIFY ("ID_RAMASSAGE" NOT NULL ENABLE);
  ALTER TABLE "RAMASSAGE" ADD CONSTRAINT "RAMASSAGE_PK" PRIMARY KEY ("ID_RAMASSAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITOYENS
--------------------------------------------------------

  ALTER TABLE "CITOYENS" ADD CONSTRAINT "PK22" PRIMARY KEY ("ID_CIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "MISSION" ADD CONSTRAINT "PK25" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARCHAND
--------------------------------------------------------

  ALTER TABLE "MARCHAND" ADD CONSTRAINT "PK24" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "RECLAMATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RECLAMATION" MODIFY ("ID_COMP" NOT NULL ENABLE);
  ALTER TABLE "RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("ID", "ID_COMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE_RAMASSAGE
--------------------------------------------------------

  ALTER TABLE "EMPLOYE_RAMASSAGE" ADD CONSTRAINT "EMPLOYE_RAMASSAGE_FK1" FOREIGN KEY ("ID_RAMASSAGE")
	  REFERENCES "RAMASSAGE" ("ID_RAMASSAGE") ENABLE;
  ALTER TABLE "EMPLOYE_RAMASSAGE" ADD CONSTRAINT "EMPLOYE_RAMASSAGE_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "EMPLOYE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "RECLAMATION" ADD CONSTRAINT "RECLAMATION_FK112" FOREIGN KEY ("ID_COMP")
	  REFERENCES "RESSOURCE" ("ID") ENABLE;
