--------------------------------------------------------
--  DDL for Table CITOYEN
--------------------------------------------------------

  CREATE TABLE "RIMA"."CITOYEN" 
   (	"ID_CIT" VARCHAR2(20 BYTE), 
	"NOM_CIT" VARCHAR2(20 BYTE), 
	"PRENOM_CIT" VARCHAR2(20 BYTE), 
	"SEXE_CIT" VARCHAR2(20 BYTE), 
	"DATE_CIT" DATE, 
	"LIEU_CIT" VARCHAR2(20 BYTE), 
	"MAIL_CIT" VARCHAR2(20 BYTE), 
	"TEL_CIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPTE
--------------------------------------------------------

  CREATE TABLE "RIMA"."COMPTE" 
   (	"IDENTIFIANT" VARCHAR2(20 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(20 BYTE), 
	"TYPE_AUTHENT" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "RIMA"."EMPLOYE" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE_MISSION
--------------------------------------------------------

  CREATE TABLE "RIMA"."EMPLOYE_MISSION" 
   (	"ID_MISSION" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE_RAMASSAGE
--------------------------------------------------------

  CREATE TABLE "RIMA"."EMPLOYE_RAMASSAGE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"ID_RAMASSAGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "RIMA"."EVENEMENT" 
   (	"ID_EVENT" VARCHAR2(20 BYTE), 
	"NOM_EVENT" VARCHAR2(20 BYTE), 
	"TYPE_EVENT" VARCHAR2(20 BYTE), 
	"DATE_EVENT" DATE, 
	"HOR_EVENT" VARCHAR2(20 BYTE), 
	"EMPL_EVENT" VARCHAR2(20 BYTE), 
	"ETAT_EVENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARCHANT
--------------------------------------------------------

  CREATE TABLE "RIMA"."MARCHANT" 
   (	"ID_MARCHANT" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMPL" VARCHAR2(20 BYTE), 
	"NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "RIMA"."MISSION" 
   (	"ID_MISSION" VARCHAR2(20 BYTE), 
	"CIN_AGENT" VARCHAR2(20 BYTE), 
	"HORAIRE_DEPART" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_EXECUT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION_MARCHANT
--------------------------------------------------------

  CREATE TABLE "RIMA"."MISSION_MARCHANT" 
   (	"ID_MISSION" VARCHAR2(20 BYTE), 
	"ID_MARCHANT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RAMASSAGE
--------------------------------------------------------

  CREATE TABLE "RIMA"."RAMASSAGE" 
   (	"ID_RAMASSAGE" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"DATE_RAMASSAGE" VARCHAR2(40 BYTE), 
	"NOMBRE_POUBELLE" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"NOM_CARTIER" VARCHAR2(20 BYTE), 
	"HEURE_DEBUT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "RIMA"."RECLAMATION" 
   (	"NOM_ROUTE" VARCHAR2(20 BYTE), 
	"TYPE_PANNE" VARCHAR2(20 BYTE), 
	"DATE_RECLAMAT" VARCHAR2(40 BYTE), 
	"NATURE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"ID_COMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESSOURCE
--------------------------------------------------------

  CREATE TABLE "RIMA"."RESSOURCE" 
   (	"TYPE_ROUTE" VARCHAR2(20 BYTE), 
	"ETAT_COMPOSANT" VARCHAR2(20 BYTE), 
	"NOM_ROUTE" VARCHAR2(20 BYTE), 
	"POSX" FLOAT(126), 
	"POSY" FLOAT(126), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ZONE_VERTE
--------------------------------------------------------

  CREATE TABLE "RIMA"."ZONE_VERTE" 
   (	"ID_ZONEVERTE" NUMBER, 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"AIRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
